version: '2'
services:
  motioneye:
    build: vividboarder/rpi-motioneye
    container_name: motioneye
    ports:
      - "8765:8765"
      - "8091:8091"
    volumes:
      - recordings:/var/lib/motioneye
volumes:
  recordings: {}
