version: '2'
services:
  motioneye:
    image: ccrisan/motioneye:dev-armhf
    container_name: motioneye
    ports:
      - "8765:8765"
      - "8091:8091"
    volumes:
      - recordings:/var/lib/motioneye
#      - ./motion.conf:/etc/motion/motion.conf
      - ./data:/var/lib/motion
      - /etc/localtime:/etc/localtime
    devices:
      - /dev/video0:/dev/video0
    restart: always
volumes:
  recordings: {}
