version: '3'
services:

  motioneye:
    image: ccrisan/motioneye:dev-armhf
    container_name: motioneye
    ports:
      - "8765:8765"
      - "8091:8091"
    volumes:
      - recordings:/var/lib/motioneye
      - ./motion.conf:/etc/motion/motion.conf
      - ./data:/var/lib/motion
      - /etc/localtime:/etc/localtime
#    devices:
#      - /dev/video0:/dev/video0
#    networks:
#      - me_nw
    restart: always
  
#  ffmpeg:
#    image: jrottenberg/ffmpeg
#    container_name: ffmpeg
#    ports:
#      - "5454:5454"
#    devices:
#      - /dev/video0:/dev/video0
#    networks:
#      - ff_nw
#    restart: always
    
volumes:
  recordings: {}
